baseURL = 'https://local.cloudev.group/'
languageCode = 'ja'
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = 'Cloud Native Local Developers Group'
theme = "terminal"
paginate = 5

[params]
  contenttypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  showLanguageSlector = true
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = true

[languages]
  [languages.ja]
    title = "Cloud Native Local Developers Group"
    weight = 1

  [languages.en]
    title = "Cloud Native Local Developers Group"
    weight = 2
