baseURL = 'https://local.cloudev.group/'
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = 'Cloud Native Local Developers Group'
theme = "terminal"
paginate = 5

[params]
  contenttypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  showLanguageSlector = true
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = true

[languages]
  [languages.ja]
    title = "Cloud Native Local Developers Group"
    languageCode = "ja"
    languageName = "Japanese"
    weight = 1
    [languages.ja.params.logo]
      logoText = "Cloud Native Local Developers Group"
      logoHomeLink = "/"

  [languages.en]
    title = "Cloud Native Local Developers Group"
    languageCode = "en"
    languageName = "English"
    weight = 2
    [languages.en.params.logo]
      logoText = "Cloud Native Local Developers Group"
      logoHomeLink = "/"

